### ISSUE TITLE
How should we add typescript and composition-api support to each project?

### ISSUE THREAD

**Issue by SeyyedKhandon** [jsilva-pt/medium-reusable-vue-components#5]
Thank you for your great article.
Actually I read a lot about cdd in vuejs, but I really have been confused, right now I stuck with a problem, which I want to add typescript and some other stuff, and finally, i want to publish the build version and not the SFC and scss files to npm, how should I do that?

**Comment by jsilva-pt** [comment]
Hello,
Sorry for the delay. I didn't see the notification of your issue.

I have no experience with typescript, so I can't give you an answer to that.
However, I will let this issue open, and if I find some time, I will try to explore and maybe write about it in another article.
